import type { ContractNode, ContractTree } from "../contracts/types.js";
import { collectAllNodes } from "../contracts/walk.js";
import { resolveAncestorSlots } from "../contracts/resolve.js";
import { join, relative } from "node:path";

/**
 * Convert a route directory path to a PascalCase type name.
 *
 * Algorithm:
 *   1. Compute relative path from routesDir
 *   2. Split into segments
 *   3. Strip bracket characters from each segment ([fundId] → fundId)
 *   4. PascalCase each segment (split on non-alphanumeric, capitalise first char)
 *   5. Join all segments
 *
 * Examples:
 *   routes/                       → Root
 *   routes/funds                  → Funds
 *   routes/funds/[fundId]         → FundsFundId
 *   routes/funds/[fundId]/overview → FundsFundIdOverview
 */
export function pathToTypeName(routePath: string, routesDir: string): string {
  const rel = relative(routesDir, routePath).replace(/\\/g, "/");
  if (!rel || rel === ".") return "Root";

  const segments = rel.split("/").filter(Boolean);
  return segments
    .map((seg) => {
      // Strip bracket chars: [fundId] → fundId
      const cleaned = seg.replace(/[[\]]/g, "");
      // PascalCase: split on non-alphanumeric, capitalise each part
      return cleaned
        .split(/[^a-zA-Z0-9]+/)
        .filter(Boolean)
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join("");
    })
    .join("");
}

/**
 * Generate .strata.types.ts content for a single route node that has layout.slots.
 */
export function generateTypeFile(
  node: ContractNode,
  routesDir: string,
): string {
  const slots = node.contract.layout?.slots;
  if (!slots) return "";

  const typeName = pathToTypeName(node.path, routesDir);
  const slotNames = Object.keys(slots);
  const requiredSlotNames = Object.entries(slots)
    .filter(([, v]) => v === "required")
    .map(([k]) => k);

  // Get inherited slots from ancestors
  const ancestorSlots = resolveAncestorSlots(node);
  const inheritedSlotNames = [...ancestorSlots.keys()];

  const lines: string[] = [
    "// AUTO-GENERATED by strata build \u2014 do not edit",
  ];

  lines.push(
    `export type ${typeName}Slots = ${
      slotNames.length > 0
        ? slotNames.map((s) => `'${s}'`).join(" | ")
        : "never"
    };`,
  );

  lines.push(
    `export type ${typeName}RequiredSlots = ${
      requiredSlotNames.length > 0
        ? requiredSlotNames.map((s) => `'${s}'`).join(" | ")
        : "never"
    };`,
  );

  lines.push(
    `export type ${typeName}InheritedSlots = ${
      inheritedSlotNames.length > 0
        ? inheritedSlotNames.map((s) => `'${s}'`).join(" | ")
        : "never"
    };`,
  );

  lines.push(
    `export type ${typeName}AllSlots = ${typeName}Slots | ${typeName}InheritedSlots;`,
  );
  lines.push("");

  return lines.join("\n");
}

/**
 * Walk the contract tree and generate .strata.types.ts for every route
 * node that declares layout.slots.
 */
export function generateAllTypes(
  tree: ContractTree,
  routesDir: string,
): { path: string; content: string }[] {
  if (!tree.routes) return [];

  const allNodes = collectAllNodes(tree.routes);
  const results: { path: string; content: string }[] = [];

  for (const node of allNodes) {
    if (!node.contract.layout?.slots) continue;
    const content = generateTypeFile(node, routesDir);
    if (content) {
      results.push({
        path: join(node.path, ".strata.types.ts"),
        content,
      });
    }
  }

  return results;
}
